### PR TITLE
Update website homepage design. 

### PR DESCRIPTION
**Pull request by nader77**
#167
#144
#143
#139

### CODE REVIEW

**Comment by nader77** [comment]
* Added favicon for all platforms.
your_generated_favicon


* Started working on the headers.
header

**Comment by nader77** [comment]
Update: Homepage basic design is complete, Need to do Pixel-perfect:
gizra-screenshot

**Comment by nader77** [comment]
Not finished: Homepage Pixel-perfect: 
your_project__the_gizra_way

Still to do, Check in Firefox and safari, Tablet and mobile.

**Comment by nader77** [comment]
Update: Pixel perfect for about us section and the contact section pixel-perfect:
your_project__the_gizra_way


your_project__the_gizra_way


Final homepage looks after pixel-perfect
gizra-screenshot

**Comment by nader77** [comment]
Responsive fixes (Flow in new homepage, Fixes in blog posts and fixes in blog pager):
responsive


After the video was recorded I updated the logo color:
_your_project__the_gizra_way

**Comment by nader77** [comment]
@amitaibu PR is ready, Only edited 6-7 files, Rest are images.

**Comment by amitaibu** [comment]
@nader77 can you attach a screenshot of the full page with the updated logo (in orange)

**Comment by nader77** [comment]
@amitaibu 
gizra_screenshot

**Comment by amitaibu** [comment]
I made some little changes, merged and deployed, thanks!

**Pull request closed without merging**
