### PR TITLE
put the new slogan in one line

### PR DESCRIPTION
**Pull request by niryariv**

### CODE REVIEW

**Comment by amitaibu** [comment]
@nader77 can you please "fix" the ballon positions

**Comment by niryariv** [comment]
need to center the text as well:

screen shot 2015-09-16 at 2 53 02 pm

**Comment by nader77** [comment]
@amitaibu @niryariv How does this look ?
Desktop:
_your_project__the_gizra_way
Tablet:
_your_project__the_gizra_way
Mobile:
_your_project__the_gizra_way

**Comment by amitaibu** [comment]
@RachelBaram fyi ^^

**Comment by amitaibu** [comment]
@nader77 looking good, please merge and deploy

**Comment by amitaibu** [comment]
(after tests are green)

**Comment by nader77** [comment]
Merged.

**Comment by nader77** [comment]
[Deployed](http://www.gizra.com/)

**Pull request closed without merging**
