### PR TITLE
Blog post: Sticky Floors and Happy Kids

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@OritGeron I've done some editing - let me know if you are ok with it, and if so, please assign to Nir for a final review.

**Comment by OritGeron** [comment]
@amitaibu that's great! 
sent to @niryariv already.

**Comment by amitaibu** [comment]
@niryariv can you please review

**Comment by amitaibu** [comment]
Merged, thanks - http://www.gizra.com/content/sticky-floors-happy-kids/

**Pull request closed without merging**
