### PR TITLE
Fix long lines on blog posts

### PR DESCRIPTION
**Pull request by guytepper**
On mobile the max characters per line would be 55-60 characters. On desktop it would be 75-80. 
Note that it only fixes the blog posts issue (#345), not the whole site (#329).

**Mobile:** [Before](https://cloud.githubusercontent.com/assets/13344923/13839076/3086cf16-ec21-11e5-995d-5e488d974cb1.png), [After](https://cloud.githubusercontent.com/assets/13344923/13839086/39ad7cfc-ec21-11e5-990c-3f3939303be8.png)
**Desktop:** [Before](https://cloud.githubusercontent.com/assets/13344923/13839130/7cfa5e58-ec21-11e5-9c37-caea5a90bb7e.png), [After](https://cloud.githubusercontent.com/assets/13344923/13839123/7479c868-ec21-11e5-8d9e-ceb56ff42dcd.png)

### CODE REVIEW

**Comment by amitaibu** [comment]
This looks like a good start.

I think it's a little too narrow for desktop (I tend to compare it to [medium](https://medium.com/@ericclemmons/javascript-fatigue-48d4011b6fc4#.84ms0vzhw)).

Also, bootlint seems to have found an error (upon `grunt serve`)

```
Running "bootlint:files" (bootlint) task
>> app/_layouts/post.html:48:7 E003 Found one or more `.row`s that were not children of a grid column or descendants of a `.container` or `.container-fluid`

1 lint error(s) found across 4 file(s).

For details, look up the lint problem IDs in the Bootlint wiki: https://github.com/twbs/bootlint/wiki
```

**Comment by guytepper** [comment]
@amitaibu What do you think the change?

Regarding bootlint - those classes caused some issues. Should I add them to the ignore list?

**Comment by amitaibu** [comment]
> What do you think about the change?

Taking the medium example they are using ~700px (although, of course, their design fits it very nicely). I saw that you've already adapted it to something similar.

> Regarding bootlint - those classes caused some issues so I had to remove them

Yeah, the PR kind of escapes from Bootstrap's classes. I wonder if it would be possible to reach a similar functionality while still playing nicely with Bootstrap.

**Comment by amitaibu** [comment]
Ok, lets merge this to fix the problem, and follow it on another PR

**Pull request merged**
