### PR TITLE
WIP: Re-design: team page.

### PR DESCRIPTION
**Pull request by YuriGizra**
#200

### CODE REVIEW

**Comment by YuriGizra** [comment]
Added markup.
Header (layered):
selection_410

photos:
selection_411

**Comment by YuriGizra** [comment]
Added smooth scroll:
scroll

hover on photo
Photos according design:
hover-photo

**Comment by YuriGizra** [comment]
@YaronMiro,
The Markup ready for review.

**Comment by amitaibu** [comment]
@YuriGizra please update title

**Comment by amitaibu** [comment]
Also, how come this is a 40 files PR?

**Comment by YuriGizra** [comment]
The branch based on branch 198. Because I use some common classes, that was changed in this branch. and added/replaced a few images.

**Comment by amitaibu** [comment]
If based on another branch, please create PR against that branch. Very hard to review 40 files...

**Comment by YaronMiro** [comment]
Closing in favor of #205

**Pull request closed without merging**
