### PR TITLE
Old- Theme single blog post page.

### PR DESCRIPTION
**Pull request by YuriGizra**
#198

### CODE REVIEW

**Comment by YuriGizra** [comment]
Header:
selection_393
Layered:
selection_392

**Comment by YuriGizra** [comment]
Headers, list:
selection_397

selection_396

Numeric list:
selection_400

blockquotes:
selection_402

selection_401

Italic:
selection_403

selection_399

**Comment by YuriGizra** [comment]
navigation and Author informaiton:
selection_405

Output:
selection_406

**Comment by YuriGizra** [comment]
@amitaibu 
Is it still part of disqus?
Should I reduce  to 2 "discovery posts"?
selection_407

**Comment by amitaibu** [comment]
I'm not sure you have this control over disqus. Anyway, not in this PR

**Comment by YuriGizra** [comment]
@amitaibu, Ready for review.

**Comment by YaronMiro** [comment]
Closing in favor of #209

**Pull request closed without merging**
