### PR TITLE
Increase "about" whitespace.

### PR DESCRIPTION
**Pull request by nader77**
#177 Follow up.

### CODE REVIEW

**Comment by nader77** [comment]
@niryariv How does this look ?
your_project__the_gizra_way

**Comment by niryariv** [comment]
ok, just add %20 more at the bottom please

**Comment by nader77** [comment]
@niryariv Done, 20% is about `25px`:
your_project__the_gizra_way

**Comment by nader77** [comment]
@amitaibu May I merge and deploy ?

**Comment by amitaibu** [comment]
can you please add a black background to the about

**Comment by nader77** [comment]
Added black background:
your_project__the_gizra_way

**Comment by nader77** [comment]
Updated padding on about section:
your_project__the_gizra_way

**Comment by nader77** [comment]
Merged.

**Pull request closed without merging**
