### PR TITLE
Post: Thinking Elm

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@niryariv ready for review.

**Comment by amitaibu** [comment]
Merged, http://www.gizra.com/content/thinking-choosing-elm/

**Comment by niryariv** [comment]
I just found a mistake (I created): "decidoe" in the last paragraph -
should be "decide"

**Comment by amitaibu** [comment]
Fixed and deployed. Thanks.

**Pull request closed without merging**
