### PR TITLE
blog: Multiple view web application with Aurelia

### PR DESCRIPTION
**Pull request by ceoaliongroo**
#160

router-with-view-ports

screen shot 2015-06-10 at 9 29 21 am

### CODE REVIEW

**Comment by ceoaliongroo** [comment]
@amitaibu, @niryariv

Draft ready, need you revision.

**Comment by amitaibu** [comment]
Can you please add a screenshot/ gif. Also maybe you can push the demo to gh-pages?

**Comment by amitaibu** [comment]
Ready for review?

**Comment by amitaibu** [comment]
This is not going to be finished, so closing. Elm is better :)

**Pull request closed without merging**
