### PR TITLE
Adding new team images

### PR DESCRIPTION
**Pull request by YaronMiro**
@DavidKohav 
You can continue from here. :)

* [x] Add Guy
* [x] Add Nir
* [x] Add Pavel

### CODE REVIEW

**Comment by DavidKohav** [comment]
Please code review and deploy
team gizra

**Comment by amitaibu** [comment]
Pavel's image looks a bit too small I think.

**Comment by YaronMiro** [comment]
Updated Pavel image ^^
team gizra

**Comment by amitaibu** [comment]
👍

**Comment by YaronMiro** [comment]
Merged manually,

**Pull request closed without merging**
