### PR TITLE
Grammar and typographical edits

### PR DESCRIPTION
**Pull request by IshaDakota**

### CODE REVIEW

**Comment by bricel** [comment]
Thank you @IshaDakota , @YaronMiro please merge and release.

**Comment by IshaDakota** [comment]
I've got some more to do. I'll change title when it's not WIP.

**Comment by YaronMiro** [comment]
Hi  @IshaDakota,

Please assign me the PR is ready and I will merge & deploy.
Thanks.

**Comment by IshaDakota** [comment]
@YaronMiro sorry for the delay - I'm done.

**Comment by YaronMiro** [comment]
@IshaDakota 
Merged and deployed.

**Pull request closed without merging**
