### PR TITLE
Fix and update the visual monitor.

### PR DESCRIPTION
**Pull request by DavidKohav**
#301

### CODE REVIEW

**Comment by DavidKohav** [comment]
Please confirm

**Comment by amitaibu** [comment]
Some base images are wrong:

* Team has a broken link, but more over - whenever we'll have a new team member it will change. I say, remove completely this page.
* Blog list page -- `exclude` isn't good here, because the height changes from post to post. I'd remove the text elements so the height is the same.

**Comment by DavidKohav** [comment]
@amitaibu - Done.

**Comment by DavidKohav** [comment]
Done

**Pull request merged**
