### PR TITLE
Configuration bootlint for gizra.

### PR DESCRIPTION
**Pull request by YuriGizra**
* checks certain files for certain error.
* The bootlint doesn't stop grunt on errors/warnings, but notice in terminal.

### CODE REVIEW

**Comment by YuriGizra** [comment]
selection_427

**Comment by YuriGizra** [comment]
@YaronMiro, ready for review

**Comment by YaronMiro** [comment]
@yuri can you please update me what is the status of this PR ?
thanks.

**Comment by YuriGizra** [comment]
@YaronMiro Fixed: skip check id in carousel:
`id="{{ id }}"`

**Comment by YaronMiro** [comment]
@yuri Please close this PR and create a new PR `master` <= `conf-lints`
The branch `re-master` is deprecated.

**Comment by YuriGizra** [comment]
Opened another PR to master

**Pull request closed without merging**
