### PR TITLE
Shoov multiple browsers

### PR DESCRIPTION
**Pull request by amitaibu**

### CODE REVIEW

**Comment by amitaibu** [comment]
@niryariv please assign to me after review (so I get notified about it)

**Comment by amitaibu** [comment]
@niryariv I've done a few fixes, but it's ready now.

**Comment by niryariv** [comment]
done editing - but im not sure i understand, does shoov replace the baseline images automatically? how do we know the images it uses are correct (ie, a page was changed, how do you avoid having a human checking all the browser snapshots?). also, what do you use the get the browser/platform snapshots?

**Comment by amitaibu** [comment]
Thanks. 

> how do you avoid having a human checking all the browser snapshots?

When there's a regression you always meed a human to check (same as with failing Behat tests)

> also, what do you use the get the browser/platform snapshots?

BrowserStack - I'll add it to the post

**Comment by amitaibu** [comment]
Merged and deployed - http://www.gizra.com/content/cross-browser-visual-regression-with-shoov/

**Pull request closed without merging**
