### PR TITLE
Homepage changes.

### PR DESCRIPTION
**Pull request by nader77**
#175
#176

### CODE REVIEW

**Comment by nader77** [comment]
@niryariv Should I remove the gold ?
##Desktop:
gizra_screenshot

##Tablet:
gizra_screenshot_tablet

##Mobile: 
gizra_screenshot_mobile

**Comment by nader77** [comment]
In mobile, text is cut Because of the screenshot, It's not really cut.

**Comment by nader77** [comment]
@niryariv @amitaibu Updated screenshots with the new about us text.
This is ready.

**Comment by niryariv** [comment]
@nader77 need to add some space about the "you might have seen our work":

space

**Comment by niryariv** [comment]
@nader77 also please remove the ":" at the end

**Comment by nader77** [comment]
@niryariv Updated:
your_project__the_gizra_way

**Comment by niryariv** [comment]
great, thanks!

**Comment by nader77** [comment]
@amitaibu Ready for code review.

**Comment by amitaibu** [comment]
You can delete the background image

**Comment by nader77** [comment]
Removed all the images that was used by the previous design.

**Comment by amitaibu** [comment]
thans, please merge + deploy

**Comment by nader77** [comment]
Merged and [deployed](http://www.gizra.com/)

**Comment by niryariv** [comment]
@nader77 please increase the space between elements above & under the text:

screen shot 2015-07-21 at 4 07 59 pm

**Pull request closed without merging**
