### PR TITLE
Remove UN logo.

### PR DESCRIPTION
**Pull request by nader77**
#188

### CODE REVIEW

**Comment by nader77** [comment]
@niryariv I thought I should change the design a little bit because we have an odd number of logos, Is this ok ?
your_project__the_gizra_way

Or should I just leave an empty space at the end ?

**Comment by amitaibu** [comment]
Is it ok on mobile?

**Comment by nader77** [comment]
Tablet:
_your_project__the_gizra_way

Mobile (Was a little bit of white space) :
_your_project__the_gizra_way

**Comment by amitaibu** [comment]
:+1:

**Comment by nader77** [comment]
Merged.

**Pull request closed without merging**
